CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE challenge (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL REFERENCES user(id),
  plan_name VARCHAR(50) NOT NULL,
  status VARCHAR(20) DEFAULT 'ACTIVE',
  starting_balance REAL NOT NULL,
  current_balance REAL NOT NULL,
  current_equity REAL NOT NULL,
  profit_target REAL NOT NULL DEFAULT 10.0,
  max_daily_loss_pct REAL NOT NULL DEFAULT 5.0,
  max_total_loss_pct REAL NOT NULL DEFAULT 10.0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE trade (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  challenge_id INTEGER NOT NULL REFERENCES challenge(id),
  symbol VARCHAR(50) NOT NULL,
  side VARCHAR(10) NOT NULL,
  quantity REAL NOT NULL,
  price REAL NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  pnl REAL DEFAULT 0.0
);

CREATE TABLE payment (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL REFERENCES user(id),
  plan_name VARCHAR(50) NOT NULL,
  amount REAL NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'DH',
  status VARCHAR(20) DEFAULT 'completed',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE paypal_config (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  client_id VARCHAR(200) NOT NULL,
  client_secret VARCHAR(200) NOT NULL,
  mode VARCHAR(20) NOT NULL DEFAULT 'sandbox'
);

